# Generated by Django 4.0.4 on 2022-05-09 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_tables_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='type',
            field=models.CharField(choices=[('L', 'league'), ('P', 'playoffs'), ('LP', 'league + playoffs')], default='L', max_length=2),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TypeTournament',
        ),
    ]
