# Generated by Django 4.0.4 on 2022-05-12 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_matches_away_goals_alter_matches_home_goals'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='type',
            field=models.CharField(choices=[('G', 'goal'), ('AG', 'auto-goal'), ('Y', 'yellow card'), ('R', 'red card')], default=None, max_length=2),
            preserve_default=False,
        ),
    ]
