# Generated by Django 4.0.4 on 2022-05-14 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_test_tables_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playoff_scheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_goals', models.PositiveIntegerField(null=True)),
                ('away_goals', models.PositiveIntegerField(null=True)),
                ('count_matches', models.PositiveSmallIntegerField(default=1)),
                ('stage', models.CharField(max_length=10)),
                ('club_away', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='club_away_pl', to='main.clubs')),
                ('club_home', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='club_home_pl', to='main.clubs')),
                ('matches', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.matches')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tournament')),
            ],
        ),
    ]
