# Generated by Django 4.0.4 on 2022-05-14 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_playoff_scheme_matches'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='text_stage',
            field=models.CharField(max_length=7, null=True),
        ),
    ]
