# Generated by Django 4.0.4 on 2022-05-14 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_matches_text_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playoff_scheme',
            name='club_away',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='club_away_pl', to='main.clubs'),
        ),
        migrations.AlterField(
            model_name='playoff_scheme',
            name='club_home',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='club_home_pl', to='main.clubs'),
        ),
    ]
