# Generated by Django 4.0.4 on 2022-05-14 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_matches_actions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matches',
            name='text_stage',
        ),
        migrations.RemoveField(
            model_name='playoff_scheme',
            name='count_matches',
        ),
        migrations.AddField(
            model_name='matches',
            name='playoff_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.playoff_scheme'),
        ),
    ]
