# Generated by Django 4.0.4 on 2022-05-14 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_matches_text_stage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='text_stage',
            field=models.CharField(max_length=7, null=True),
        ),
    ]
