# Generated by Django 4.0.4 on 2022-05-16 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_playoff_scheme_away_goals_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='rounds',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
