# Generated by Django 4.0.4 on 2022-05-16 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_clubs_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='text_stage',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
