# Generated by Django 4.0.4 on 2022-05-17 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_matches_text_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='uid',
            field=models.CharField(default='dadsadsadAS2', max_length=20),
            preserve_default=False,
        ),
    ]
