# Generated by Django 4.0.4 on 2022-05-19 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_tables_goals_difference'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubs',
            name='contact_info',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='matches',
            name='matchday',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='cards',
            field=models.PositiveIntegerField(default=4),
        ),
    ]
