# Generated by Django 4.0.4 on 2022-05-21 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_tournament_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubs',
            name='contact_info',
        ),
        migrations.AddField(
            model_name='clubs',
            name='notes',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
