# Generated by Django 4.0.4 on 2022-05-21 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_remove_clubs_contact_info_clubs_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubs',
            name='notes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
