# Generated by Django 4.0.4 on 2022-05-21 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_clubs_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubs',
            name='notes',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
