# Generated by Django 4.0.4 on 2022-05-22 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_clubs_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='distribution_rules',
            field=models.CharField(default='GD_GF_M', max_length=20),
            preserve_default=False,
        ),
    ]
