# Generated by Django 4.0.4 on 2022-05-23 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_alter_matches_away_goals_alter_matches_home_goals'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='count_clubs',
            field=models.PositiveIntegerField(default=3),
            preserve_default=False,
        ),
    ]
