# Generated by Django 4.0.4 on 2022-05-23 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_tournament_count_clubs'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='serial_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
