# Generated by Django 4.0.4 on 2022-05-30 10:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0034_alter_tournament_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='admins', to=settings.AUTH_USER_MODEL),
        ),
    ]
