# Generated by Django 4.0.4 on 2022-07-19 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_alter_tournament_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='type',
            new_name='kind',
        ),
    ]
